title: Cloud-Recon
description: Azure field insights from Wayne Marks
baseurl: "/Azure-Blog"
url: "https://cloud-recon.github.io"
theme: null

# Enable remote theme
remote_theme: mmistakes/minimal-mistakes

# Minimal Mistakes theme options
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

# Author settings
author:
  name   : "Wayne Marks"
  avatar : "/assets/images/Cloud-Recon.webp"
  bio    : "Azure CSA | Real-world networking from the field"

# Social settings (optional)
social:
  type: Person
  name: Wayne Marks
  links:
    - https://www.linkedin.com/in/waynemarkscloud
