title: Cloud-Recon
description: Azure blog from a CSA
baseurl: "/Azure-Blog"          # repo name
url: "https://cloud-recon.github.io"

theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

# IMPORTANT: remove any previous 'defaults:' or 'stylesheets:' overrides
# Cayman will automatically load /assets/css/style.css if we provide style.scss
