title: Cloud-Recon
description: Azure blog from a CSA
baseurl: "/Azure-Blog"
url: "https://cloud-recon.github.io"

theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

# Tell Jekyll to use our custom stylesheet
defaults:
  -
    scope:
      path: ""
    values:
      stylesheets:
        - /assets/css/override.css
