title: Cloud-Recon
description: Azure blog from CSA Wayne
baseurl: "/Azure-Blog"
url: "https://cloud-recon.github.io"
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

# Keep your site-wide stylesheet override
defaults:
  - scope:
      path: ""
    values:
      stylesheets:
        - /assets/css/override.css

# NEW: collection for live previews (safe, does not touch _posts)
collections:
  preview:
    output: true
    permalink: /preview/:name/
